//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstaArt.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class comments
    {
        public int id { get; set; }
        public int id_photo { get; set; }
        public int id_user { get; set; }
        public string message { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual photos photos { get; set; }
        public virtual users users { get; set; }
    }
}
