//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstaArt.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_relations
    {
        public int id { get; set; }
        public int id_user { get; set; }
        public int id_subscriber { get; set; }
        public int relation { get; set; }
    
        public virtual relation relation1 { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
