//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstaArt
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyAppET2 : DbContext
    {
        public MyAppET2()
            : base("name=MyAppET2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<comments> comments { get; set; }
        public virtual DbSet<group> group { get; set; }
        public virtual DbSet<group_photo> group_photo { get; set; }
        public virtual DbSet<likes> likes { get; set; }
        public virtual DbSet<photos> photos { get; set; }
        public virtual DbSet<photos_tags> photos_tags { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<subs> subs { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tags> tags { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<users_photo> users_photo { get; set; }
        public virtual DbSet<users_tags> users_tags { get; set; }
    }
}
